/*
* generated by Xtext
*/
package org.example.domainmodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DomainmodelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
